### ISSUE TITLE
Maps SDK (18.0.x) update by June for Android

### ISSUE THREAD

**Issue by Wian-TMC** [martin-braun/google_maps_place_picker_mb#10]
As of June 2022, the default renderer for Google Maps on Android is 18.0.x. As we are using this package which in turn uses Google Maps, is this a dependency applicable to this Repo, or is this related to the version of `google_maps_flutter` being used within this package?

If this package is dependent on the `google_maps_flutter` package, it might be wise to look out for this update and ensure this package remains up to date with the `google_maps_flutter` pub package.

**Comment by martin-braun** [comment]
We have to keep an eye on this line of code: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/android/build.gradle#L38

Once this gets updated to version 18.x.x, I have to update `google_maps_flutter` to the version that is listed here ASAP: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/pubspec.yaml#L5

**Comment by martin-braun** [comment]
@Wian-TMC The changes have been done, thus I updated the packages, thus the new Maps SDK is being used. Please update and kindly report back (if there are more problems). :)
