### ISSUE TITLE
Searched address not reflected on map

### ISSUE THREAD

**Issue by manpreetpatil** [martin-braun/google_maps_place_picker_mb#12]
**Describe the bug**
Search location by move pin working fine but when i search and select address from autocomplete then selected address first reflect on map and then after few second it override with current address. I've tested this on Android. I've latest version of plugin.

**To Reproduce**
1. Search location 
2. select address from autocomplete
3. searched address will be replaced with current location

**Comment by martin-braun** [comment]
I remember this bug and I remember that I fixed it in this version. Are you sure you pulled the MB version? (`2.0.0-mb.14` is current)

I tried to reproduce this on my device again, but it's working for me. Can you please tell me on which device you are testing? I would really appreciate if you could upload a screen recording if this is happening on `2.0.0-mb.14`.
