### ISSUE TITLE
Search bar is overlapped with search results when typing

### ISSUE THREAD

**Issue by AhmadRehan71** [martin-braun/google_maps_place_picker_mb#13]
When user type in the search bar the search results dialog overlap on the search bar, and the content on the search bar field is no more visible to user.

**Comment by martin-braun** [comment]
Yes, I have seen this on the original repo in https://github.com/fysoul17/google_maps_place_picker/issues/159 and I want to address this when I have some time for it.

**Comment by martin-braun** [comment]
Try with the recent build (mb 15). Should work now. :)

**Comment by AhmadRehan71** [comment]
@martin-braun  Thanks it works
