### ISSUE TITLE
Some locations fail silently

### ISSUE THREAD

**Issue by poqueque** [martin-braun/google_maps_place_picker_mb#15]
Some locations from Search bar fail. The cursor just moves a bit and it shows an error on console.

**To Reproduce**
1. Go to Search Bar
2. Search for this location: "Wallmart Supercenter, American Boulevard East, Bloomington, MN, USA"
3. Click on location found
4. The cursor does not move to expected location
5. This error appear on console:

```
E/flutter (25625): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (25625): Receiver: null
E/flutter (25625): Tried calling: []("adr_address")
E/flutter (25625): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (25625): #1      _$PlaceDetailsFromJson (package:google_maps_webservice/src/places.g.dart:136:21)
E/flutter (25625): #2      new PlaceDetails.fromJson (package:google_maps_webservice/src/places.dart:710:7)
E/flutter (25625): #3      _$PlacesDetailsResponseFromJson (package:google_maps_webservice/src/places.g.dart:294:26)
E/flutter (25625): #4      new PlacesDetailsResponse.fromJson (package:google_maps_webservice/src/places.dart:838:7)
E/flutter (25625): #5      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:528:29)
E/flutter (25625): #6      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:126:12)
E/flutter (25625): <asynchronous suspension>
E/flutter (25625): #7      _PlacePickerState._pickPrediction (package:google_maps_place_picker_mb/src/place_picker.dart:389:44)
```

Tested with v2.0.0-mb.15 on iOS and Android.

**Comment by martin-braun** [comment]
For me it is working without problems on my Pixel 3A device as well as on the iPhone Simulator: 

![2022-04-04 12 49 23 AM](https://user-images.githubusercontent.com/24259245/161452219-b9c19b91-3ffa-4f2f-8c5f-04a7d1bd363a.gif)

Could you please run the example app in this repo and set a break-point here: https://github.com/martin-braun/google_maps_place_picker_mb/blob/master/lib/src/place_picker.dart#L389

It would be nice if you could report all the values that are passed to `getDetailsByPlaceId()` for further inspection. It seems the Google Maps API returned invalid JSON, almost looks like a bug on Googles end. 

- If the example app works and yours not, you might want to compare and break down a copy of your app to a minimal sample that you could share, if you don't find the cause
- If the example app also causes the issue, I can only imagine that there is a problem outside of the code scope. Where are you located, what does `flutter doctor -v` report and are you using the latest Flutter version?

On the latter case, please press F12 of the `getDetailsByPlaceId()` function to jump to its implementation that looks like this: 

```dart
  Future<PlacesDetailsResponse> getDetailsByPlaceId(
    String placeId, {
    String? sessionToken,
    List<String> fields = const [],
    String? language,
    String? region,
  }) async {
    final url = buildDetailsUrl(
      placeId: placeId,
      sessionToken: sessionToken,
      fields: fields,
      language: language,
      region: region,
    );
    return _decodeDetailsResponse(await doGet(url, headers: apiHeaders));
  }
```

Put a break-point after `final url = ...` to reveal the URL that is being requested when searching for that place. You might want to try to access this address using Postman.

It's really weird that only some addresses fail. That indicates that your session need to be valid, but the service doesn't want to delivery details to the place.

I'm curious about your findings, thanks for investigating further.

**Comment by poqueque** [comment]
Working without problem right now. Yes, it looks like it was a bug on Google end that it's already fixed...

**Comment by martin-braun** [comment]
Awesome, thanks for reporting back. :)
