### ISSUE TITLE
How to get user's chosen maptype?

### ISSUE THREAD

**Issue by gtu-myowin** [martin-braun/google_maps_place_picker_mb#17]
I saw that this package is using provider to set and get maptype. Is there any way to get the user's chosen maptype on "onPlacePicked" callback?

I want this feature because I would like to use the exact map type the user was chosen while picking the location.

Thank you in advance.

**Comment by martin-braun** [comment]
Hi @gtu-myowin, I don't think to.

`PickResult` will be built out of `GeocodingResult` or `PlaceDetails` (Google API) which doesn't provide such information as far as I am aware of.

However, if we expose the provider and expand it with an `getMapType` function it should be possible to read out the map type after picking a place.

I have to look into it when I have more time, though.

**Comment by gtu-myowin** [comment]
Noted with thanks!

**Comment by martin-braun** [comment]
@gtu-myowin Please update to `2.0.0-mb.16`. You can now track changes by subscribing to a new event on the `PlacePicker` like so: 

```dart
onMapTypeChanged: (MapType mapType) {
	print("Map type changed to ${mapType.toString()}");
},
```

[Full example](https://github.com/martin-braun/google_maps_place_picker_mb/blob/master/example/lib/main.dart#L89)

Have fun! :)
