### ISSUE TITLE
usePinPointingSearch false keep loading

### ISSUE THREAD

**Issue by nomanmurtaza786** [martin-braun/google_maps_place_picker_mb#2]
I have marked usePinPointingSearch to false. After that loader keeps on loading
![Simulator Screen Shot - iPhone 13 - 2021-10-21 at 01 19 31](https://user-images.githubusercontent.com/14288484/138112072-4ca25801-b665-4f92-a62e-0935dc3a4ed2.png)
.

**Comment by hardiklakhalani** [comment]
Same issue here.
plus I'm seeing this as well..

![image](https://user-images.githubusercontent.com/82162165/200833343-3a2ab4f0-8e24-4e0d-a39e-f40833bcda82.png)

**Comment by martin-braun** [comment]
@hardiklakhalani You should properly setup all the APIs on the Google Cloud. Please work yourself through the README.
