### ISSUE TITLE
Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?'

### ISSUE THREAD

**Issue by yigitcevik** [martin-braun/google_maps_place_picker_mb#23]
Hello, I installed the package using the specified paths and used the sample code you provided. When I try to run the application, I get the following error. How do I resolve this error?

![mappickererror](https://user-images.githubusercontent.com/38765433/170819587-fd73c09d-2813-4d46-8daf-9b50c4ace7d3.png)

**Comment by martin-braun** [comment]
Can you please try to update Flutter to `3.0.1` or use `mb.18` for now. There were recent breaking changes in Flutter, so we have to introduce breaking changes for past versions as well, see #22.

**Comment by yigitcevik** [comment]
> Can you please try to update Flutter to `3.0.1` or use `mb.18` for now? There were recent breaking changes in Flutter, so we have to introduce breaking changes for past Flutter versions as well to fix it for the most recent version, see #22.

I got the same problem when I did mb18 but when I updated Flutter the problem went away. Right now, the map opens properly. However, when I searched for an address and selected it, I encountered the following error: 
`No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_8 `
Line 165 of the file C:\src\flutter\packages\flutter\lib\src\services\platform_channel.dart throws this error.

**Comment by yigitcevik** [comment]
> > Can you please try to update Flutter to `3.0.1` or use `mb.18` for now? There were recent breaking changes in Flutter, so we have to introduce breaking changes for past Flutter versions as well to fix it for the most recent version, see #22.
> 
> I got the same problem when I did mb18 but when I updated Flutter the problem went away. Right now, the map opens properly. However, when I searched for an address and selected it, I encountered the following error: `No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_8 ` Line 165 of the file C:\src\flutter\packages\flutter\lib\src\services\platform_channel.dart throws this error.

It was fixed when I closed and opened the emulator completely. :)
