### ISSUE TITLE
selectInitialPosition: true is not working

### ISSUE THREAD

**Issue by shanu95** [martin-braun/google_maps_place_picker_mb#26]
**Describe the bug**
Even with the added selectInitialPosition: true, it doesn't show the picked place when open the map first time. even change the location it doesn't show up floating card. Floating card is only show when i search a place.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter Doctor -v**
[✓] Flutter (Channel stable, 3.0.2-0.0.pre.2, on macOS 12.4 21F79 darwin-arm
    (Rosetta), locale en-GB)
    • Flutter version 3.0.2-0.0.pre.2 at /Users/daredevil/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0a488d1a76 (3 minutes ago), 2022-06-01 21:30:21 +0530
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/daredevil/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • SM G970F (mobile) • RF8M223FMRP • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.4 21F79
      darwin-arm (Rosetta)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      98.0.4758.80
    ! Error: Alexis’s iPhone is not connected. Xcode will continue when Alexis’s
      iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Additional context**
```
Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => PlacePicker(
                                hintText: "Enter plot location",
                                apiKey:
                                    "API_KEY", // Put YOUR OWN KEY here.

                                initialPosition: kInitialPosition,
                                useCurrentLocation: true,
                                selectInitialPosition: true,
                                usePinPointingSearch: true,
                                usePlaceDetailSearch: true,
                                zoomGesturesEnabled: true,
                                zoomControlsEnabled: true,
                                onPlacePicked: (result) {
                                  //print(result.address);
                                  _plotlocationController.text =
                                      result.formattedAddress!;
                                  print(result.formattedAddress);
                                  print(result.placeId);
                                  print(result.geometry!.location);
                                  print(result.types);
                                  Navigator.of(context).pop();
                                  setState(() {});
                                },
                              ),
                            ),
                          );
```

**Comment by martin-braun** [comment]
Flutter Version `3.0.2-0.0.pre.2` is not listed for me. The current stable is `3.0.1` and the beta is `3.1.0`. I tested both versions and unfortunately, I cannot reproduce the issue in both versions on Android and iOS. The floating card appears immediately on start. Could you try to disable `useCurrentLocation` and see if the `initialPosition` will be selected, immediately?

Could you also try to run the [example app](https://github.com/martin-braun/google_maps_place_picker_mb/tree/master/example) after pulling this repository?

Are you sure that `selectedPlaceWidgetBuilder` is not set? To investigate further you could also set it like so: 

```dart
selectedPlaceWidgetBuilder: (_, selectedPlace, state, isSearchBarFocused) {
	print("state: $state, isSearchBarFocused: $isSearchBarFocused");
}
```

This will prevent the floating card from showing up, but it would allow you to see if the code is reached and the state is printed. Please give me the output. 

Finally on which device are you testing this?

**Comment by shanu95** [comment]
> Flutter Version `3.0.2-0.0.pre.2` is not listed for me. The current stable is `3.0.1` and the beta is `3.1.0`. I tested both versions and unfortunately, I cannot reproduce the issue in both versions on Android and iOS. The floating card appears immediately on start. Could you try to disable `useCurrentLocation` and see if the `initialPosition` will be selected, immediately?
> 
> Could you also try to run the [example app](https://github.com/martin-braun/google_maps_place_picker_mb/tree/master/example) after pulling this repository?
> 
> Are you sure that `selectedPlaceWidgetBuilder` is not set? To investigate further you could also set it like so:
> 
> ```dart
> selectedPlaceWidgetBuilder: (_, selectedPlace, state, isSearchBarFocused) {
> 	print("state: $state, isSearchBarFocused: $isSearchBarFocused");
> }
> ```
> 
> This will prevent the floating card from showing up, but it would allow you to see if the code is reached and the state is printed. Please give me the output.
> 
> Finally on which device are you testing this?

I had tried with useCurrentLocation : false as you mentioned and it is picking the initial place immediately. And i'm sure that i havent added selectedPlaceWidgetBuilder property. I had added it as you mentioned and it is printing this only -> "state: SearchingState.Searching, isSearchBarFocused: false". My device is samsung s10e with Android 12 and Samsung One UI 4.1.
<img width="767" alt="Screenshot 2022-06-06 at 10 45 55 PM" src="https://user-images.githubusercontent.com/39364254/172211558-e181ff5e-5420-402d-8ef5-d690d8e9f03a.png">
<img width="573" alt="Screenshot 2022-06-06 at 10 46 19 PM" src="https://user-images.githubusercontent.com/39364254/172211616-e9f73bd7-2475-4ccb-9fbc-ab8232a09215.png">

**Comment by shanu95** [comment]
Check the screen recording here -> https://youtu.be/c83K2ceZSts

**Comment by martin-braun** [comment]
> I had tried with useCurrentLocation : false as you mentioned and it is picking the initial place immediately.

So with `useCurrentLocation: false` everything works as expected?

> Check the screen recording here -> [youtu.be/c83K2ceZSts](https://youtu.be/c83K2ceZSts)

I see how even dragging will not resolve the state. It should really print two states, but it seems it will never reach the `SearchingState.Idle` unless you go through the search bar. The state after init and camera drag will be set to idle within the `_searchByCameraLocation` function that is load when `selectInitialPosition` is true or when the `debounceTimer` on `onCameraIdle` fires. 

If you checkout the [`_searchByCameraLocation`](https://github.com/martin-braun/google_maps_place_picker_mb/blob/master/lib/src/google_map_place_picker.dart#L104) you will figure out that it will always set the `provider.placeSearchingState` to `SearchingState.Idle` unless the `provider.geocoding.searchByLocation` call finishes. 

If you check logcat you probably will find the cause of the issue, but I think I can tell you right away: 

Google Maps provides different APIs for different tasks. Searching by location is a different API than searching by string. Please check if you have enabled "Geocoding API", "Geolocation API" and "Places API". If you have, please share your relevant logcat logs, so we can look further.

I will await your response, thank you.

**Comment by shanu95** [comment]
> > Check the screen recording here -> [youtu.be/c83K2ceZSts](https://youtu.be/c83K2ceZSts)
> 
> The floating card is only displayed, when the search state reaches `SearchingState.Idle`. I see how even dragging will not resolve the state. It should really print two states, but it seems it will never reach the `SearchingState.Idle` unless you go through the search bar. The state after init and camera drag will be set to idle within the `_searchByCameraLocation` function that is load when `selectInitialPosition` is true or when the `debounceTimer` on `onCameraIdle` fires.
> 
> If you checkout the [`_searchByCameraLocation`](https://github.com/martin-braun/google_maps_place_picker_mb/blob/master/lib/src/google_map_place_picker.dart#L104) you will figure out that it will always set the `provider.placeSearchingState` to `SearchingState.Idle` unless the `provider.geocoding.searchByLocation` call stalls.
> 
> If you check logcat you probably will find the cause of the issue, but I think I can tell you right away:
> 
> Google Maps provides different APIs for different tasks. Searching by location is a different API than searching by string. Please check if you have enabled "Geocoding API", "Geolocation API" and "Places API". If you have, please share your relevant logcat logs, so we can look further.
> 
> I will await your response, thank you. I hope this is the actual cause of the problem, or we have a bigger problem. :)

Yes it's working after enable the Geocoding API and Geolocation API. I had only enabled the sdk for ios/android and places API. I think it's better you mentioned to enabled those API's as well in the readme file. Thank you for the help.

**Comment by martin-braun** [comment]
> Yes it's working after enable the Geocoding API and Geolocation API. I had only enabled the sdk for ios/android and places API. I think it's better you mentioned to enabled those API's as well in the readme file. Thank you for the help.

You are welcome, but [it is mentioned in the readme file](https://github.com/martin-braun/google_maps_place_picker_mb#getting-started), already. It's always useful to read the readme carefully, before opening an issue. You probably just missed that section.
