### ISSUE TITLE
Custom selectedPlaceWidgetBuilder not updating selected place always return SearchingState.Searching true.

### ISSUE THREAD

**Issue by anil-sookshum** [martin-braun/google_maps_place_picker_mb#30]
Trying to use a custom selectedPlaceWidgetBuilder with the PlacePicker widget as it always returns the "state 
 == SearchingState.Searching" on location change on Map i.e drag to a new location. 
 
Screen Recording: [place_picker_issue_with_custom_selectedPlaceWidgetBuilder](https://drive.google.com/file/d/19vWgoYjnR89AW1kIXUMQ5j5uVPhHqbuq/view?usp=sharing)
 
 Steps to replicate:
 - Run the Example App on iOS simulator
 - Add a selectedPlaceWidgetBuilder
    
```
selectedPlaceWidgetBuilder: (_, selectedPlace, state, isSearchBarFocused) {
        print('state: $state, isSearchBarFocused: $isSearchBarFocused');
        return isSearchBarFocused
            ? Container()
             : FloatingCard(
                  bottomPosition:
                     20.0, // MediaQuery.of(context) will cause rebuild. See MediaQuery document for the information.
                     leftPosition: 10.0,
                      rightPosition: 10.0,
                      width: 500,
                        height: 50,
                        borderRadius: BorderRadius.circular(12.0),
                        child: state == SearchingState.Searching
                            ? const Center(child: CircularProgressIndicator())
                            : ElevatedButton(
                                child: const Text('Pick Here'),
                                onPressed: () {
                                  // IMPORTANT: You MUST manage selectedPlace data yourself as using this build will not invoke onPlacePicker as
                                  //            this will override default 'Select here' Button.
                                  print('do something with [selectedPlace] data');
                                  Navigator.of(context).pop();
                                },
                              ),
                      ),
     };
    ```
 - Restart (Shift+R)
 
(Possibly a state management issue the state is updating if I manually do a hot reload (Shift+r).

Plugin V: latest from dart pub
Flutter V: 3.0.1

**Comment by anil-sookshum** [comment]
> 
> Screen Recording: [place_picker_issue_with_custom_selectedPlaceWidgetBuilder](https://drive.google.com/file/d/19vWgoYjnR89AW1kIXUMQ5j5uVPhHqbuq/view?usp=sharing)
> 
> Steps to replicate:
> 
> * Run the Example App on iOS simulator
> * Add a selectedPlaceWidgetBuilder
> 
> ```
> selectedPlaceWidgetBuilder: (_, selectedPlace, state, isSearchBarFocused) {
>         print('state: $state, isSearchBarFocused: $isSearchBarFocused');
>         return isSearchBarFocused
>             ? Container()
>              : FloatingCard(
>                   bottomPosition:
>                      20.0, // MediaQuery.of(context) will cause rebuild. See MediaQuery document for the information.
>                      leftPosition: 10.0,
>                       rightPosition: 10.0,
>                       width: 500,
>                         height: 50,
>                         borderRadius: BorderRadius.circular(12.0),
>                         child: state == SearchingState.Searching
>                             ? const Center(child: CircularProgressIndicator())
>                             : ElevatedButton(
>                                 child: const Text('Pick Here'),
>                                 onPressed: () {
>                                   // IMPORTANT: You MUST manage selectedPlace data yourself as using this build will not invoke onPlacePicker as
>                                   //            this will override default 'Select here' Button.
>                                   print('do something with [selectedPlace] data');
>                                   Navigator.of(context).pop();
>                                 },
>                               ),
>                       );
>                     ```
>  - Restart (Shift+R)
>  
> 
>  
> ```

**Comment by martin-braun** [comment]
> The floating card is only displayed, when the search state reaches `SearchingState.Idle`. I see how even dragging will not resolve the state. It should really print two states, but it seems it will never reach the `SearchingState.Idle` unless you go through the search bar. The state after init and camera drag will be set to idle within the `_searchByCameraLocation` function that is load when `selectInitialPosition` is true or when the `debounceTimer` on `onCameraIdle` fires. 
> 
> If you checkout the [`_searchByCameraLocation`](https://github.com/martin-braun/google_maps_place_picker_mb/blob/master/lib/src/google_map_place_picker.dart#L104) you will figure out that it will always set the `provider.placeSearchingState` to `SearchingState.Idle` unless the `provider.geocoding.searchByLocation` call stalls. 
> 
> If you check logcat you probably will find the cause of the issue, but I think I can tell you right away: 
> 
> Google Maps provides different APIs for different tasks. Searching by location is a different API than searching by string. Please check if you have enabled "Geocoding API", "Geolocation API" and "Places API". If you have, please share your relevant logcat logs, so we can look further.
> 
> I will await your response, thank you. I hope this is the actual cause of the problem, or we have a bigger problem. :)

_Originally posted by @martin-braun in https://github.com/martin-braun/google_maps_place_picker_mb/issues/26#issuecomment-1147950228_
