### ISSUE TITLE
PickResult Variable selectedPlace intitialize error

### ISSUE THREAD

**Issue by Muraleedharank** [martin-braun/google_maps_place_picker_mb#31]
While loading the page it shows selectedPlace cannot be initialized.In the following section
 selectedPlace == null
                  ? Container()
                  : Text(selectedPlace.formattedAddress ?? ""),

**Comment by martin-braun** [comment]
- Could you please copy paste the error for me? 
- Could you also paste the output of `flutter doctor -v`? 
- Could you tell me on which device/emulator you are testing? 
- Could you tell me the exact steps to reproduce?

**Comment by martin-braun** [comment]
Closed due to inactivity.
