### ISSUE TITLE
Getting search results from other countries only

### ISSUE THREAD

**Issue by dpedrinha** [martin-braun/google_maps_place_picker_mb#32]
**Describe the bug**
I'm in Brazil and I'm having a very hard time getting local results. All the results are from other countries. Sometimes they don't even fit the search criteria.

**To Reproduce**
Set the emulator location to somewhere in Brazil (I'm using -16.127842, -52.481918).
Use the initialPosition LatLng(-16.127842, -52.481918)
Run the plugin and search for places nearby
Examples:
'amtt' returns 'amtR" results even though there is an AMTT business in the region.
'red dot' returns "red dot" results from other countries even though there is a Red Dot Customs business in the region.
On my device maps or browser if I search for those two I immediately get the correct suggestion.
I don't know if it has anything to do with the plugin or if it's google map's api fault but I thought I had to bring it up to you.

**Expected behavior**
It should prioritize nearby results.

**Comment by martin-braun** [comment]
I'm confident that this is solely an emulator problem, but I will investigate nonetheless when I have time for it. Thank you for your report.

**Comment by dpedrinha** [comment]
I've tested on my device and the problem persists.

I found out the predictions api may use an optional parameter to set the region code to restrict results. I'll try using it and see if the results are improved.

**Comment by dpedrinha** [comment]
That's it.

Using the `region `parameter fixed the problem. Now I'm getting relevant results.

I thought the api would use our location automatically for that. Weird that it doesn't.

**Comment by martin-braun** [comment]
@dpedrinha Great. Can you share the detailed steps so others who have the same problem and find this issue know how to fix it in detail? I.e. where to add the `region` parameter exactly. A code sample shall be appreciated.

**Comment by Dereumaux-Adrien** [comment]
This workaround doesn't seem like enough as it depends on your locale.
If you travel abroad without changing your phone's locale, you will still see results from your home country.
For example, my phone is set in British English, so my search only show results in the UK, no matter where I am at the moment.

A good workaround would be to authorize the use of:

`PlacesSearchResponse response = await places.searchNearbyWithRankby(new Location(31.0424, 42.421), "distance");`
which is available in the https://pub.dev/packages/google_maps_webservice package.

**Comment by martin-braun** [comment]
@Dereumaux-Adrien Very weird. When I test my American English emulator I still get results from my country (Germany). It could be enough to set the region of your current country on `PlacePicker`, it should not?

Maybe an option is to offer a flag that allows you to search near-by? I assume the issue with `searchNearbyWithRankby` is that you cannot find stuff far away, so it shall be optional.

**Comment by Dereumaux-Adrien** [comment]
@martin-braun If you still get all the results from germany, I don't think that will work with all use cases. If you look for a big chain of restaurants like mc donalds, do you get the most "famous" mc donalds in germany or the closest to your position?

The use of a small `autocompleteRadius` seems to be correcting this issue I had and still allow for searches of far away places (as long as you provide enough details in the search of course).
