### ISSUE TITLE
How to expose the Geometry object?

### ISSUE THREAD

**Issue by dpedrinha** [martin-braun/google_maps_place_picker_mb#35]
Hi, this is not a bug, but I don't know how else to ask this.

I'm trying to get the lat and lng from the picker but the `Geometry` object returned from `result.geometry` doesn't autocomplete and I can't import it.

Here's what I'm doing:

```
MaterialPageRoute(
          builder: (context) => PlacePicker(
            apiKey: MySharedPreferences.GMAPS_API_KEY,
            region: mainModel.countryCode,
            onPlacePicked: (PickResult result) {
              _updateTxtFields(
                name: result.name ?? '',
                description: '',
                phones: result.formattedPhoneNumber ?? '',
                website: result.website ?? '',
                address: result.formattedAddress ?? '',
                latLang: _formatLatLang(result.geometry),
              );
              Navigator.of(context).pop();
            },
```

```
String _formatLatLang(Geometry geometry) { //throws Undefined class Geometry
      String result = '';
      if(geometry != null) {
        //where I'd do my string formating
      }
      return result;
    }
```

Geometry throws Undefined class and there's no Geometry class to import. It should already be exposed by the plugin import but for some reason it is not working.

If I pass the entire PickResult object, it works. I can access `result.geometry!.location.lat` with no problem.

Any idea of what I'm doing wrong?

**Comment by martin-braun** [comment]
You can access `result.geometry.location.lat` and `result.geometry.location.lng` directly. If you want to use the Geometry class (i.e. for passing it around), you have to add `google_maps_webservice: ^0.0.20-nullsafety.5` to your pubspec.yaml.

Pick predictions as well as detail data loading is done via http. I don't know why not and if Google provides better interfaces (by now), but the original author of this package used to abstract it with the `google_maps_webservice` package by building an own provider that uses it and handles all the necessary requests.

So here we are. Please do not hesitate to reply if something is still unclear.
