### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by martin-braun** [martin-braun/google_maps_place_picker_mb#4]
Can you merge [#150@google_maps_place_picker](https://github.com/fysoul17/google_maps_place_picker/pull/150/) to your fork to fix this issue?

_Originally posted by @Chrg1001 in https://github.com/fysoul17/google_maps_place_picker/issues/140#issuecomment-970285447_

**Comment by martin-braun** [comment]
@Chrg1001 Please get the new version and report if it was successful. :)

**Comment by Chrg1001** [comment]
@martin-braun It works! Thank you!

**Comment by martin-braun** [comment]
@Chrg1001 You're welcome. :)
