### ISSUE TITLE
How to hide the back arrow next to the search input?

### ISSUE THREAD

**Issue by giorgio79** [martin-braun/google_maps_place_picker_mb#49]
I just noticed a back arrow appearing next to the search bar.

Can we hide it somehow? :)

PS Just seeing this feature "onTapBack" probably will implement it if it cannot be hidden :)

![image](https://user-images.githubusercontent.com/283347/215284720-e06cd6bc-eb1a-40ac-a8bc-9642267463ff.png)

**Comment by giorgio79** [comment]
Just implemented onTapBack so I guess it can stay :P

**Comment by martin-braun** [comment]
It's always better to give that user the opportunity to cancel  the map picking. Well done!
