### ISSUE TITLE
current location not working 

### ISSUE THREAD

**Issue by sajjatdev** [martin-braun/google_maps_place_picker_mb#52]
current location not working 

<i>Notice by @martin-braun:

> If you experience similar problems, please install 3.0.0 until this problem is fixed.</i>

**Comment by martin-braun** [comment]
could've be any issue on your end. I.e. missing APIs, not setting up a location in your Simulator, etc. Please [follow the instructions](https://github.com/martin-braun/google_maps_place_picker_mb#getting-started) and post your logcat and device if this won't help. Maybe you understand the root cause by reading the logcat by your own, it's often trivial.

**Comment by rehamalraee24** [comment]
same here

**Comment by Sparks1998** [comment]
You have removed the get location code from the `place_provider.dart => updateCurrentLocation method`

**Comment by martin-braun** [comment]
@Sparks1998 We replaced FlutterLocation with Geolocator in #51. Please share the output of `flutter doctor` and tell me what you are testing on (Android Emulator, Apple Simulator, Device?). Some logs (logcat, device logs) are also helpful.

@giorgio79 Location service is working fine for you on Android / iOS?

**Comment by giorgio79** [comment]
Yes works just fine. Have it in production for thousands of users.

**Comment by martin-braun** [comment]
@giorgio I'm testing with the example app in the Android Emulator and Apple Simulator and the current location indeed can't be load on my end. Have you tested your changes in Simulator / Emulator by configuring a custom location in its settings?

**Comment by giorgio79** [comment]
Travelling at the moment for two weeks with limited internet. I tested with simulator, device and various locations. Havent played with the example app! 
Any specific error messages? If none, its probably a permission issue. 
PS Location package is dead, so downgrading will most likely cause plenty of other issues...
https://github.com/Lyokone/flutterlocation/issues

**Comment by martin-braun** [comment]
@giorgio79 Np, and yes, downgrading is not an option. I just wanted to point out that's an option for everybody who uses this package and experiences the same problems. I'm still very busy on a project, but maybe I can tackle this before you are back. Enjoy your trip. :)

**Comment by giorgio79** [comment]
Thx Martin! :) I am pretty sure this is a permission request issue. In my app I request that separately from this package on the first screens like Tinder... Using the copy paste geolocator code here https://pub.dev/packages/geolocator
Probably that is why it worked for me just fine. Might be a good idea to offload that task from this app 😊

**Comment by martin-braun** [comment]
@giorgio79 You nailed it, thanks for the input. Yes, the map picker asked for permission, previously. This needs to be brought back to the module itself. It was solved in a way that it would only ask for permission, when it didn't get permission already.

**Comment by martin-braun** [comment]
Should work now.

**Comment by OVOgenez** [comment]
When the location service is disabled, permission is not requested to enable it (it is only checked, and if it is missing, it returns an error).
