### ISSUE TITLE
Current location takes 10 seconds to load on iOS

### ISSUE THREAD

**Issue by martin-braun** [martin-braun/google_maps_place_picker_mb#8]
@martin-braun thank you for your support your package is working but the current location button on iOS always takes 10seconds to 12seconds
can you please let me know how to fix it 

PS: on android, the button working properly.

REGARDS

_Originally posted by @SmarterVision in https://github.com/fysoul17/google_maps_place_picker/issues/163#issuecomment-1026845468_

**Comment by martin-braun** [comment]
@SmarterVision Can you please provide some more details (i.e. device logs when it happens)? I'm very busy right now, but I can try to check it out this week. Please also tell me if this is happening in the simulator and which device/simulator you've tested.

**Comment by SmarterVision** [comment]
hi @martin-braun It is not working in my iPhone 12 (take 10 seconds to get my current location )
but t's working fine in the simulator (iPhone 12)

**Comment by martin-braun** [comment]
@SmarterVision Can you please pull this project and run the example app (debug) on the device and [log the output](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Access-Device-Console-Logs and share your relevant logs)? 

I do not own an iPhone 12, thus I rely on your help now.

**Comment by gsoykan** [comment]
Hey! @SmarterVision @martin-braun  you can check my solution for this on [original repos issue](https://github.com/fysoul17/google_maps_place_picker/issues/43#issuecomment-1049752540).

**Comment by martin-braun** [comment]
@gsoykan Thanks for your report and support, means a lot to me. I'd love to hear back from @SmarterVision in regards of this as well, since I updated the `geolocator` almost a month before @SmarterVision was reporting the issue.

I can only assume that he depended on version 7 on himself in some way. I close this and hopefully I don't have to re-open it. 😄

**Comment by martin-braun** [comment]
@gsoykan Thank you for your great investigation and help, that means a lot to me. 

I currently have some publishing issues here at the moment. Once they are solved and the next version is published I will close this issue as it should be solved then. Please pull the new version when it's ready, then you can remove your dependency to the `geolocator` again.

**Comment by martin-braun** [comment]
New version 2.0.0-mb.14 is up. Pull it and it should be fixed without the need of a more recent `geolocator` package in your pubspec.
